version: '3'
services:
  controller-bot:
    build: ./bot/
    container_name: "controller_bot_ok"
  database:
    image: "bitnami/postgresql:13.3.0-debian-10-r47" # use latest official postgres version
    container_name: "database"
    environment:
      - POSSTGRES_USER=postgres
      - POSTGRESQL_DATABASE=bot_database
      - POSTGRESQL_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  spider:
    build: ./spider/
    container_name: "mention_counter"
volumes:
  database-data:
